version: '3.9'

services:
  fastapi:
    build: ai-service
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - ai-service/.env
    environment:
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}
    depends_on:
      - keycloak
    volumes:
      - ./app:/app
    restart: unless-stopped

  springboot:
    build: AI-BasedRecommendationTool
    container_name: springboot-app
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - AI_SERVICE_URL=http://fastapi:8000
    depends_on:
      - keycloak
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    env_file:
      - ai-service/.env
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
    volumes:
      - C:/Users/gabri/Keycloak/keycloak-26.3.1/keycloak-26.3.1/data:/opt/keycloak/data
      - C:/Users/gabri/Keycloak/import:/opt/keycloak/data/import
    restart: unless-stopped


