version: '3.9'

services:
  fastapi:
    build: AI-service
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - keycloak
    volumes:
      - ./app:/app
    restart: unless-stopped

  springboot:
    build: Main-Service
    container_name: springboot-app
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - AI_SERVICE_URL=${AI_SERVICE_URL}
      - RESTPROJECT_BASEURL=${RESTPROJECT_BASEURL}
    depends_on:
      - keycloak
      - fastapi
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak
    command:
      - start-dev
      # Uncomment only after placing a realm export in keycloak/import
      # - --import-realm
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
    # volumes:
    #   - ./keycloak/import:/opt/keycloak/data/import
    restart: unless-stopped
