package dataelementhub.relation.service.aiService;

import dataelementhub.relation.model.aiModel.*;
import dataelementhub.relation.model.scoredElement.RelationAnalysisResult;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.List;

/**
 * Client service for communicating with external AI-based relation analysis services.
 *
 * This component acts as an integration layer between the relation mapping
 * workflow and the NLP service. It is responsible for preparing requests,
 * invoking AI endpoints, and transforming the returned results into
 * application-specific objects.
 *
 * Currently, the service supports:
 * - One-to-many NLP relation analysis
 * - Many-to-many NLP relation analysis
 */
@Service
@RequiredArgsConstructor
public class AIClient {
    // HTTP client used to communicate with the external AI service.
    private final RestTemplate restTemplate = new RestTemplate();
    // Base URL of the NLP service providing relation analysis endpoints.
    @Value("${ai.service.url}")
    private String aiBaseUrl;

    /**
     * Performs NLP-based relation analysis between one reference text
     * and multiple candidate texts.
     *
     * The method sends a request to the external NLP service and retrieves
     * similarity and relation scores generated by the underlying AI models.
     *
     * @param text1 Reference text item.
     * @param text2List Candidate text items.
     * @return List of NLP relation analysis results.
     */
    public List<RelationAnalysisResult> getNLPRelationOneToMany(TextItem text1, List<TextItem> text2List) {
        // Measure execution time for performance evaluation.
        long start = System.nanoTime();
        // Build the request payload expected by the NLP service.
        SimilarityRequest request = new SimilarityRequest();
        request.setText1(text1);
        request.setText2_list(text2List);

        // Invoke the one-to-many NLP relation analysis endpoint.
        NlpRelationResponse response = restTemplate.postForObject(
                aiBaseUrl + "/relationUsingNlp/one-to-many",
                request,
                NlpRelationResponse.class
        );

        // Log execution time for monitoring and thesis evaluation.
        long end = System.nanoTime();
        double seconds = (end - start) / 1_000_000_000.0;
        System.out.println("NLP call took: " + seconds + " seconds");

        // Return the NLP results or an empty list if no response is available.
        return response != null ? response.getResults() : List.of();
    }

    /**
     * Performs NLP-based relation analysis between multiple reference texts
     * and multiple candidate texts.
     *
     * The method delegates the relation analysis to the external NLP service
     * and returns the generated similarity and relation scores for all
     * source-target combinations.
     *
     * @param text1 List of reference text items.
     * @param text2List List of candidate text items.
     * @return List of NLP relation analysis results.
     */
    public List<RelationAnalysisResult> getNLPRelationManyToMany(List<TextItem> text1, List<TextItem> text2List) {
        // Measure execution time for performance evaluation.
        long start = System.nanoTime();

        // Build the request payload for many-to-many analysis.
        SimilarityRequest request = new SimilarityRequest();
        request.setText1_list(text1);
        request.setText2_list(text2List);

        // Invoke the many-to-many NLP relation analysis endpoint.
        NlpRelationResponse response = restTemplate.postForObject(
                aiBaseUrl + "/relationUsingNlp/many-to-many",
                request,
                NlpRelationResponse.class
        );

        // Record execution time for performance measurements.
        long end = System.nanoTime();
        double seconds = (end - start) / 1_000_000_000.0;
        System.out.printf("NLP many-to-many call took: %.3f seconds%n", seconds);

        // Return the NLP results or an empty list if no response is available.
        return response != null ? response.getResults() : List.of();
    }

}
